### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by luyifan** [luyifan/ClassificationAndDetection#1]
# To do
- [x] Change cluster boxes color
- [x] Realize the compression and squareness function 
- [x] Change the display of image flow and not just square
- [x] Change suppression method if two object locate closely but  with different high label 
- [x] Improve the display when no much answer of detection
- [x] Improve the display when too much answer of detection and we can't see image
